name: Reusable deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      docker_compose_file:
        required: true
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, "${{ inputs.environment }}"]
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Environment File
        run: |
          echo "DB_USER=${{ vars.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_DATABASE=${{ vars.DB_DATABASE }}" >> .env
          echo "DB_HOST=${{ vars.DB_HOST }}" >> .env
          echo "DB_PORT=${{ vars.DB_PORT }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_SECRET=${{ vars.DB_SSL }}" >> .env

      - name: Run docker-compose
        run: |
          docker-compose -f ${{ inputs.docker_compose_file }} up -d
