name: Manual Deploy

on:
  workflow_dispatch:

jobs:
  trigger-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "production"
      docker_compose_file: "docker-compose.prod.yml"
    secrets: inherit
